# ==============================================================================
# Chart values
# ==============================================================================
chart: 
  nameOverride: ""
  fullnameOverride: ""
  
# ==============================================================================
# Ingress values
# ==============================================================================
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
  # nginx.ingress.kubernetes.io/rewrite-target: /
  # nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  # nginx.ingress.kubernetes.io/use-regex: 'true'
  # tls:
  #   - hosts:
  #       - example.com
  #     secretName: example-tls
  rules:
    - host: vastaya.tech
      paths:
        - path: /
          pathType: Prefix
          servicePort: 80
          # servicePortName: http

# ==============================================================================
# Service values
# ==============================================================================
service:
  annotations: 
    mirror.linkerd.io/exported: "true"
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    # - port: 443
    #   targetPort: 8443
    #   protocol: TCP
    #   name: https

# ==============================================================================
# Deployment values
# ==============================================================================
deployment:
  annotations: {}
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  imagePullSecrets: []
  podSecurityContext: {}
  volumes: [
    # {
    #   "name": "foo",
    #   "secret": {
    #     "secretName": "mysecret",
    #     "optional": false
    #   }
    # }  
  ]
  nodeSelector: {}
  tolerations: []
  # affinity: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - application
# ==============================================================================
# Container values
# ==============================================================================,
container:
  securityContext: {
    # readOnlyRootFilesystem: true,
    # runAsNonRoot: true,
    # runAsUser: 1000
  }
  image:
    # repository: localhost:32773
    name: application 
    pullPolicy: IfNotPresent
    tag: latest
  # env:
  # Not needed as setting them will require a rebuild of the image
  # - name: REACT_APP_USERS_API_URL
  #   value: http://users.vastaya.tech/
  # - name: REACT_APP_PROJECTS_API_URL
  #   value: http://projects.vastaya.tech/
  # This won't work because the users-service is not exposed to the internet and the React app is running in the browser
  # - name: REACT_APP_USERS_API_URL
  #   value: http://users-service.default.svc.cluster.local:3001
  livenessProbe:
    httpGet:
      path: /
      port: 80
  readinessProbe:
    httpGet:
      path: /
      port: 80
  resources: {
    # "requests": {
    #   "cpu": "100m",
    #   "memory": "128Mi"
    # },
    # "limits": {
    #   "cpu": "250m",
    #   "memory": "256Mi"
    # }
  }
  volumeMounts: [
    # {
    #   "name": "foo",
    #   "mountPath": "/foo",
    #   "readOnly": true
    # }
  ]

# ==============================================================================
# Service Account values
# ==============================================================================
serviceAccount:
  # name: ""
  enabled: false
  annotations: {}
  automount: true

# ==============================================================================
# Horizontal Pod values
# ==============================================================================
horizontalPodAutoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80