apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: backend-split
  namespace: trafficsplit-sample
spec:
  service: projects-vastaya-svc
  backends:
  - service: projects-vastaya-svc
    port: 80
    weight: 0
  - service: tasks-vastaya-svc
    port: 80
    weight: 1000