# ==============================================================================
# Chart values
# ==============================================================================
chart: 
  nameOverride: ""
  fullnameOverride: ""
  
# ==============================================================================
# Ingress values
# ==============================================================================
ingress:
  enabled: false
  # className: nginx
  # className: webapprouting.kubernetes.azure.com
  # annotations:
  # nginx.ingress.kubernetes.io/rewrite-target: /
  # nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  # nginx.ingress.kubernetes.io/use-regex: 'true'
  # tls:
  #   - hosts:
  #       - example.com
  #     secretName: example-tls
  # rules:
  #   - host: vastaya.tech
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #         servicePort: 80
          # servicePortName: http
        # - path: /secure
        #   pathType: Prefix
        #   servicePortName: https

# ==============================================================================
# Service values
# ==============================================================================
service:
  # type: ClusterIP
  # ports:
  #   - port: 80
  #     targetPort: 1337
  #     protocol: TCP
  #     name: http
  #   - port: 443
  #     targetPort: 8443
  #     protocol: TCP
  #     name: https

# ==============================================================================
# Deployment values
# ==============================================================================
deployment:
  # annotations: {}
  # replicaCount: 1
  # podAnnotations: {}
  # podLabels: {}
  # imagePullSecrets: []
  # podSecurityContext: {}
  # volumes: [
  #   {
  #     "name": "foo",
  #     "secret": {
  #       "secretName": "mysecret",
  #       "optional": false
  #     }
  #   }  
  # ]
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}

# ==============================================================================
# Container values
# ==============================================================================
container:
  # securityContext: {
  #   readOnlyRootFilesystem: true,
  #   runAsNonRoot: true,
  #   runAsUser: 1000
  # }
  # image:
  #   repository: localhost
  #   name: projects
  #   pullPolicy: IfNotPresent
  #   tag: latest
  # env:
  # - name: PORT
  #   value: 1337
  # - name: DB_HOST
  #   value: mysql-cluster.default.svc.cluster.local
  # - name: DB_PORT
  #   value: 3306
  # - name: DB_USER
  #   value: root
  # - name: DB_PASSWORD
  #   value: sakila
  # - name: DB_NAME
  #   value: testdb
  # livenessProbe:
  #   httpGet:
  #     path: /api/healthz
  #     port: 1337
  #   initialDelaySeconds: 10
  #   periodSeconds: 10
  #   failureThreshold: 3
  # readinessProbe:
  #   httpGet:
  #     path: /api/readyz
  #     port: 1337
  #   initialDelaySeconds: 10
  #   periodSeconds: 10
  #   failureThreshold: 3
  # resources: {
  #   "requests": {
  #     "cpu": "100m",
  #     "memory": "128Mi"
  #   },
  #   "limits": {
  #     "cpu": "250m",
  #     "memory": "256Mi"
  #   }
  # }
  # volumeMounts: [
  #   {
  #     "name": "foo",
  #     "mountPath": "/foo",
  #     "readOnly": true
  #   }
  # ]

# ==============================================================================
# Service Account values
# ==============================================================================
serviceAccount:
  enabled: false
  # name: ""
  # annotations: {}
  # automount: true

# ==============================================================================
# Horizontal Pod values
# ==============================================================================
horizontalPodAutoscaler:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80