{{- if and .Values.galaxies.enabled .Values.galaxies.serviceAccount.create .Values.galaxies.rbac.create }}
{{- $labels := dict "root" . "name" "galaxies-api" "component" "galaxies-api" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole-galaxies-api
  labels:
    {{- include "vastaya.standardLabels" $labels | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "delete"]
{{- end }}
