apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: enterprise-2.16.0-0
      license: eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCdW95YW50IEluYyIsInN1YiI6ImxpY2Vuc2UiLCJhdWQiOiJCdW95YW50IiwiZXhwIjo0MTAyNDQ0ODAwLCJDbGllbnRJRCI6IlVZemluazYxZU02WVBVVWMiLCJDbGllbnRTZWNyZXQiOiI3ZmRiY2E3YWIwZmFjNGQ5YjI1MjliYTJhOWExODM4ZDg4YWIyN2YwMTZhMjg0NjRkZDdmODViZDNjYmU4NzdmIiwiUHJvZHVjdCI6IkJFTCIsIlZlcnNpb24iOjIsIk1hbmFnZWRDb250cm9sUGxhbmVFbmFibGVkIjp0cnVlLCJNYW5hZ2VkRGF0YVBsYW5lRW5hYmxlZCI6dHJ1ZSwiRW50ZXJwcmlzZUVuYWJsZWQiOnRydWUsIkhBWkxFbmFibGVkIjp0cnVlLCJGSVBTRW5hYmxlZCI6dHJ1ZSwiUGF0Y2hSZWxlYXNlc0VuYWJsZWQiOnRydWV9.GL6kZ6N8Oj4yfWXwr3YYRx4mRBNqtwdYe9SxcbIaIVriPp5BLfIsgl6sXfuU-y_q4U502HxnjUFq3eQvtJQAnQ
      controlPlaneConfig:
        proxy:
          image:
            version: enterprise-2.16.0
          # additionalEnv:
          #   - name: BUOYANT_BALANCER_LOAD_LOW
          #     value: "0.1"
          #   - name: BUOYANT_BALANCER_LOAD_HIGH
          #     value: "100000.0"
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQa2pLLX1lZeS8s5XvOvtu9jAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNDEwMDQxMjQy
          MzNaFw0zNDEwMDIxMjQyMzNaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEh1vNrberrrrFDwzA
          DkiaiYahNYUeByT/MXkL4UiIR1e+fZIF2i0zW7wx6H2EUR5Nf9+hdCenH3qCek+M
          FFGwBqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFBIYrGRFEm187MnLuAOOlB2ns7GqMAoGCCqGSM49BAMCA0gAMEUCIGep
          xLCTC5eWwF+4DbyCl8GzxeAX1wBPgzUmccWyQUNVAiEAlGlBh8eUO7rfeAPq6so1
          zS/8b1AFyzt0HhPMr1uYmxI=
          -----END CERTIFICATE-----
        identity:
          issuer:
            scheme: kubernetes.io/tls
        # destinationController:
        #   experimentalArgs:
        #   - -ext-endpoint-zone-weights
