# ==============================================================================
# Chart values
# ==============================================================================
chart: 
  nameOverride: ""
  fullnameOverride: ""
  
# ==============================================================================
# Ingress values
# ==============================================================================
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    # nginx.ingress.kubernetes.io/proxy-no-cache: "true"
    # nginx.ingress.kubernetes.io/proxy-revalidate: "true"
    # nginx.ingress.kubernetes.io/proxy-cache-bypass: "true"
    # linkerd.io/inject: enabled
  # nginx.ingress.kubernetes.io/rewrite-target: /
  # nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  # nginx.ingress.kubernetes.io/use-regex: 'true'
  # tls:
  #   - hosts:
  #       - example.com
  #     secretName: example-tls
  rules:
    - host: projects.vastaya.tech
      paths:
        - path: /
          pathType: Prefix
          servicePort: 80
          # servicePortName: http

# ==============================================================================
# Service values
# ==============================================================================
service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    # - port: 443
    #   targetPort: 8443
    #   protocol: TCP
    #   name: https

# ==============================================================================
# Deployment values
# ==============================================================================
deployment:
  annotations: {}
  replicaCount: 1
  podAnnotations: 
    # config.alpha.linkerd.io/proxy-enable-native-sidecar: "true"
    # ad.datadoghq.com/tasks-vastaya-cntr.checks: |
    #   {
    #     "linkerd": {
    #       "init_config": {},
    #       "instances": [{"openmetrics_endpoint": "http://%%host%%:4191/metrics"}]
    #     }
    #   }    
  podLabels: {}
  imagePullSecrets: []
  podSecurityContext: {}
  volumes: [
    # {
    #   "name": "foo",
    #   "secret": {
    #     "secretName": "mysecret",
    #     "optional": false
    #   }
    # }  
  ]
  nodeSelector: {}
  tolerations: []
  affinity: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - application
# ==============================================================================
# Container values
# ==============================================================================
container:
  securityContext: {
    # readOnlyRootFilesystem: true,
    # runAsNonRoot: true,
    # runAsUser: 1000
  }
  image:
    # repository: localhost:32773
    name: projects
    pullPolicy: IfNotPresent
    tag: latest
  # env:
  # - name: REACT_APP_TASKS_API_URL
  #   value: http://projects.vastaya.tech/
  livenessProbe:
    httpGet:
      path: /healthz
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /readyz
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  resources: {
    # "requests": {
    #   "cpu": "100m",
    #   "memory": "128Mi"
    # },
    # "limits": {
    #   "cpu": "250m",
    #   "memory": "256Mi"
    # }
  }
  volumeMounts: [
    # {
    #   "name": "foo",
    #   "mountPath": "/foo",
    #   "readOnly": true
    # }
  ]

# ==============================================================================
# Service Account values
# ==============================================================================
serviceAccount:
  enabled: false
  # name: ""
  # annotations: {}
  # automount: true

# ==============================================================================
# Horizontal Pod values
# ==============================================================================
horizontalPodAutoscaler:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80