# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: linkerd-trust-anchor
#   namespace: linkerd
# spec:
#   ca:
#     secretName: linkerd-trust-anchor
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd-viz
spec:
  ca:
    secretName: linkerd-trust-anchor