apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: linkerd-control-plane
spec:
  components:
    linkerd:
      version: PLACEHOLDER_VERSION
      license: PLACEHOLDER_LICENSE
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
PLACEHOLDER_CERTIFICATE
        identity:
          issuer:
            scheme: kubernetes.io/tls