apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vastaya-frontend.fullname" . }}
  labels:
    {{- include "vastaya-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vastaya-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vastaya-frontend.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PORT
              value: "80"
            - name: USERS_URL
              value: {{ .Values.env.usersUrl | quote }}
            - name: GALAXIES_URL
              value: {{ .Values.env.galaxiesUrl | quote }}
            - name: PLANETS_URL
              value: {{ .Values.env.planetsUrl | quote }}
            - name: COMMENTS_URL
              value: {{ .Values.env.commentsUrl | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
