linkerd-control-plane:
  controllerReplicas: 1
  # enablePodAntiAffinity: true # Enable pod high availability
  controllerLogLevel: debug
  policyController:
    logLevel: debug
  proxyInit:
    runAsRoot: true
  destinationController:
    additionalArgs:
    - -ext-endpoint-zone-weights
  proxy:
    additionalEnv:
    - name: BUOYANT_BALANCER_LOAD_LOW
      value: '0.1'
    - name: BUOYANT_BALANCER_LOAD_HIGH
      value: '3.0'
  # licenseResources:
  #   resources: 
  #     requests:
  #       cpu: "250m"
  #       memory: "128Mi"
  #     limits:
  #       cpu: "500m"
  #       memory: "256Mi"