{
 "title": "HAZL Demo",
 "time": { "from": "2024-10-10T17:02:13.170Z", "to": "2024-10-10T17:32:13.172Z" },
 "panels": [
  {
   "title": "CPU Usage per Kubernetes Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic Rate (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (label_topology_kubernetes_io_zone) (\n rate(node_network_transmit_bytes_total[5m]) / 1024\n * on (node) group_left(label_topology_kubernetes_io_zone)\n max(kube_node_labels{label_topology_kubernetes_io_zone!=\"\", label_agentpool!=\"default\"}) by (node, label_topology_kubernetes_io_zone)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Traffic Rate (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (label_topology_kubernetes_io_zone) (\n rate(node_network_receive_bytes_total[5m]) / 1024\n * on (node) group_left(label_topology_kubernetes_io_zone)\n max(kube_node_labels{label_topology_kubernetes_io_zone!=\"\", label_agentpool!=\"agentpool\"}) by (node, label_topology_kubernetes_io_zone)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound traffic organized by destination zone and initial zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  tcp_read_bytes_total{direction=\"outbound\", namespace=~\"vastaya\"}\n) by (namespace, pod, instance, dst_zone, src_zone)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}