MINIKUBE_CLEANUP=false
MINIKUBE_ENABLED=true
MINIKUBE_DRIVER=docker
MINIKUBE_RUNTIME=docker
MINIKUBE_CPUS=4
MINIKUBE_MEMORY=4096 # 4 GB - 12288 # 12 GB
MINIKUBE_CLUSTERS_COUNT=1
MINIKUBE_NODES_COUNT=2

LINKERD_CLEANUP=false
LINKERD_ENABLED=true
LINKERD_INJECT=true
# LINKERD_VERSION=2024.5.3 #2.16.1 - 2.15.2  edge-24.5.3
LINKERD_VERSION=2.16.2 #2.16.1 - 2.15.2  edge-24.5.3 - 2024.5.3
LINKERD_VIZ_ENABLED=true
LINKERD_FAILOVER_ENABLED=false
LINKERD_HTTP_ROUTE_ENABLED=false
BUOYANT_OPERATOR=false 
BUOYANT_CLOUD_ENABLED=true
BUOYANT_AGENT_NAME=minikube

APP_CLEANUP=false
APP_BUILD_ENABLED=true
APP_PUSH_ENABLED=true
APP_DEPLOY_ENABLED=true
APP_REGISTRY_SERVER=localhost:5000

NGINX_ENABLED=true
ARGO_ENABLED=false # TODO: to complete the installation
DATADOG_ENABLED=false # TODO: to complete the installation
CERT_MANAGER_ENABLED=false # TODO: fix the issue with the cert-manager installation
GRAFANA_ENABLED=false
PROMETHEUS_ENABLED=false
PROMETHEUS_LINKERD_VIZ_FEDERATION_ENABLED=false
K6_LOAD_TEST_ENABLED=true












NCLOUD_ENABLED=false
LINKERD_MULTICLUSTER_ENABLED=false
METRIC_SERVER_ENABLED=true
APP_TRAFFIC_ENABLED=false