apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
  - name: ubuntu
    image: curlimages/curl:latest
    command: ["sleep", "infinity"]