apiVersion: v1
kind: Pod
metadata:
  name: grpc-test
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
  - name: grpcurl
    image: fullstorydev/grpcurl:latest-alpine
    command: ["sleep", "infinity"]
    # command: ["/bin/sh", "-c", "sleep 3650d"]