apiVersion: batch/v1
kind: Job
metadata:
  name: bot-get-projects
  namespace: vastaya
spec:
  template:
    spec:
      containers:
      - name: project-creator
        image: curlimages/curl:7.78.0 
        command: ["/bin/sh", "-c"] 
        args:
        - |
          # API_URL="http://projects.vastaya.tech/"
          API_URL="http://projects-vastaya-svc.vastaya.svc.cluster.local"

          get_projects() {
            local num_requests=$1
            echo "Getting $num_requests projects..."
            for i in $(seq 1 $num_requests); do
              (
                echo "Getting project $i..."
                GET_RESPONSE=$(curl -s -X GET "$API_URL")
                echo $GET_RESPONSE
              ) &
            done
            wait
          }

          wait_time=10

          for num_requests in 50 500 5000 10000; do
            echo "Running with $num_requests requests..."
            get_projects $num_requests
            echo "Waiting for $wait_time seconds before increasing requests..."
            sleep $wait_time
          done
      restartPolicy: Never
  backoffLimit: 1
