# ==============================================================================
# Chart values
# ==============================================================================
chart: 
  nameOverride: ""
  fullnameOverride: ""
  
# ==============================================================================
# Ingress values
# ==============================================================================
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  rules:
    - host: projects.vastaya.tech
      paths:
        - path: /
          pathType: Prefix
          servicePort: 50051

# ==============================================================================
# Service values
# ==============================================================================
service:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc

# ==============================================================================
# Deployment values
# ==============================================================================
deployment:
  annotations: {}
  replicaCount: 1
  podAnnotations: 
    ad.datadoghq.com/tasks-vastaya-cntr.checks: |
      {
        "linkerd": {
          "init_config": {},
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:4191/metrics",
              "extra_metrics": [{"outbound_http_route_request_duration_seconds_bucket":"outbound_http_route_request_duration_seconds_bucket"}]
            }
          ]
        }
      }  
  podLabels: {}
  imagePullSecrets: []
  podSecurityContext: {}
  volumes: []
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: agentpool
                operator: In
                values:
                  - application

# ==============================================================================
# Container values
# ==============================================================================
container:
  securityContext: {}
  image:
    name: projects
    pullPolicy: IfNotPresent
    tag: latest
  ports:
    - containerPort: 50051
      protocol: TCP
      name: grpc
  env: {}
  livenessProbe:
    tcpSocket:
      port: 50051
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    tcpSocket:
      port: 50051
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  resources: {}
  volumeMounts: []

# ==============================================================================
# Service Account values
# ==============================================================================
serviceAccount:
  enabled: false

# ==============================================================================
# Horizontal Pod values
# ==============================================================================
horizontalPodAutoscaler:
  enabled: false