linkerd-control-plane:
  controllerReplicas: 10
  # enablePodAntiAffinity: true # Enable pod high availability
  controllerLogLevel: debug
  policyController:
    logLevel: debug
  proxyInit:
    runAsRoot: true
  destinationController:
    additionalArgs:
    - -ext-endpoint-zone-weights
  proxy:
    additionalEnv:
    - name: BUOYANT_BALANCER_LOAD_LOW
      value: '0.1'
    - name: BUOYANT_BALANCER_LOAD_HIGH
      value: '3.0'