name: Terraform Validation

on:
  pull_request:
    branches:
      - main
#    paths:
#      - 'terraform/**' 

jobs:
  validate_terraform:
    name: Validate and Scan Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/ncloud
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Use your required version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

      - name: Run Checkov Scan
        run: checkov -d . --skip-download --download-external-modules true --skip-check CKV_TF_1,CKV_TF_2
        continue-on-error: true

  initialize_and_infracost:
    name: Initialize and Cost Estimate
    runs-on: ubuntu-latest
    needs: validate_terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. --format=json --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Generate Infracost diff
        run: |
          infracost diff --path=. --format=json --compare-to=/tmp/infracost-base.json --out-file=/tmp/infracost.json

      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{ github.token }} \
                                     --pull-request=${{ github.event.pull_request.number }} \
                                     --behavior=update

